name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: wcjiang
          POSTGRES_DB: typenexus-base
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Builder Lib & Example
        run: npm run build

      # - name: Run tests with Postgres
      #   env:
      #     POSTGRES_HOST: localhost
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: wcjiang
      #     POSTGRES_DB: typenexus-base
      #   run: |
      #     npm test

      - name: Run example base tests with Postgres 
        working-directory: examples/base
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: wcjiang
          POSTGRES_DB: typenexus-base
        run: |
          npm install
          npm run test